In [1]:
import numpy as np
import numpy.linalg as la

# 1. Matrices and the basic matrix operations

In [2]:
A = np.array([[0, -1, 2], [1, 0, 1], [1, 1, 0]])
B = np.array([[-1, 0, 3], [2, 1, 0], [1, 3, -5]])

print(A)

[[ 0 -1  2]
 [ 1  0  1]
 [ 1  1  0]]


In [3]:
print(B)

[[-1  0  3]
 [ 2  1  0]
 [ 1  3 -5]]


## Multiplying a matrix with a real number

In [4]:
print(5*A)

[[ 0 -5 10]
 [ 5  0  5]
 [ 5  5  0]]


## Sum of matrices

In [5]:
print(A + B)

[[-1 -1  5]
 [ 3  1  1]
 [ 2  4 -5]]


## Matrix multiplication

Matrix multiplication is not commutative.

In [6]:
print(A.dot(B))

[[  0   5 -10]
 [  0   3  -2]
 [  1   1   3]]


In [7]:
print(B.dot(A))

[[ 3  4 -2]
 [ 1 -2  5]
 [-2 -6  5]]


In Python the * operator denotes the elementwise multiplication, not the matrix product.

In [8]:
print(A * B)

[[0 0 6]
 [2 0 0]
 [1 3 0]]


## Transpose of a matrix

The transpose $A^T$ of a matrix $A$ is defined by
\begin{equation*}
A^T(i, j) = A(j, i).
\end{equation*}

In [9]:
print(A.T)

[[ 0  1  1]
 [-1  0  1]
 [ 2  1  0]]


# 2. The inverse matrix

The set of equations 
\begin{equation*}
\left\{ \begin{aligned}
x + y - z &= -2 \\
x - 2y + z &= 5 \\
-2x + y + z &= 2
\end{aligned}\right.
\end{equation*}
is equivalent to the matrix equation
\begin{equation*}
A X = B,
\end{equation*}
where
\begin{equation*}
A = \pmatrix{1 & 1 & -1 \\ 1& -2& 1\\ -2& 1& 1}, \quad B = \pmatrix{ -2\\ 5\\ 2}\quad\text{and}\quad
X = \pmatrix{ x\\ y\\ z}.
\end{equation*}

The matrix equation can be solved as
\begin{equation*}
\begin{aligned}
AX &= B \\
\Leftrightarrow\quad A^{-1} A X &= A^{-1} B \\
\Leftrightarrow\quad I X &= A^{-1} B \\
\Leftrightarrow\quad X &= A^{-1} B
\end{aligned}
\end{equation*}

In [10]:
A = np.array([[1, 1, -1], [1, -2, 1], [-2, 1, 1]])
B = np.array([[-2], [5], [2]])

X = la.inv(A).dot(B)

print(X)

[[2.]
 [1.]
 [5.]]


The inverse matrix $A^{-1}$ is defined by
\begin{equation*}
A^{-1} A = A A^{-1} = I
\end{equation*}
where $I$ is the identity matrix with the property
\begin{equation*}
I A = A I = A
\end{equation*}
for all matrices $A$.

In [11]:
print(la.inv(A).dot(A))

[[ 1.00000000e+00  5.55111512e-17 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [12]:
print(A.dot(la.inv(A)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
